import { PropertyFieldConfig } from "@/types/editor";

export const commonLayoutSchema: PropertyFieldConfig[] = [
  {
    key: "width",
    label: "Width",
    type: "text",
    category: "layout",
    responsive: true,
    placeholder: "100%, 800px, auto",
    defaultValue: "100%",
  },
  {
    key: "maxWidth",
    label: "Max Width",
    type: "text",
    category: "layout",
    responsive: true,
    placeholder: "1200px, 100%, none",
    defaultValue: "none",
  },
  {
    key: "minHeight",
    label: "Min Height",
    type: "text",
    category: "layout",
    responsive: true,
    placeholder: "auto, 400px, 100vh",
    defaultValue: "auto",
  },
  {
    key: "display",
    label: "Display Mode",
    type: "select",
    category: "layout",
    responsive: true,
    options: [
      { label: "Block", value: "block" },
      { label: "Flex", value: "flex" },
      { label: "Grid", value: "grid" },
      { label: "Inline-Block", value: "inline-block" },
    ],
    defaultValue: "flex",
  },
  {
    key: "flexDirection",
    label: "Flex Direction",
    type: "select",
    category: "layout",
    responsive: true,
    options: [
      { label: "Column (Vertical)", value: "column" },
      { label: "Row (Horizontal)", value: "row" },
      { label: "Row Reverse", value: "row-reverse" },
      { label: "Column Reverse", value: "column-reverse" },
    ],
    defaultValue: "column",
  },
  {
    key: "justifyContent",
    label: "Align Primary (Justify)",
    type: "select",
    category: "layout",
    options: [
      { label: "Start", value: "flex-start" },
      { label: "Center", value: "center" },
      { label: "End", value: "flex-end" },
      { label: "Space Between", value: "space-between" },
      { label: "Space Around", value: "space-around" },
    ],
    defaultValue: "flex-start",
  },
  {
    key: "alignItems",
    label: "Align Cross (Items)",
    type: "select",
    category: "layout",
    options: [
      { label: "Stretch", value: "stretch" },
      { label: "Center", value: "center" },
      { label: "Start", value: "flex-start" },
      { label: "End", value: "flex-end" },
    ],
    defaultValue: "stretch",
  },
  {
    key: "gap",
    label: "Gap (px)",
    type: "number",
    category: "layout",
    responsive: true,
    min: 0,
    max: 120,
    step: 4,
    defaultValue: 16,
  },
  {
    key: "overflow",
    label: "Overflow",
    type: "select",
    category: "layout",
    options: [
      { label: "Visible", value: "visible" },
      { label: "Hidden", value: "hidden" },
      { label: "Auto Scroll", value: "auto" },
    ],
    defaultValue: "visible",
  },
];

export const commonSpacingSchema: PropertyFieldConfig[] = [
  {
    key: "paddingTop",
    label: "Padding Top",
    type: "number",
    category: "spacing",
    responsive: true,
    min: 0,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "paddingRight",
    label: "Padding Right",
    type: "number",
    category: "spacing",
    responsive: true,
    min: 0,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "paddingBottom",
    label: "Padding Bottom",
    type: "number",
    category: "spacing",
    responsive: true,
    min: 0,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "paddingLeft",
    label: "Padding Left",
    type: "number",
    category: "spacing",
    responsive: true,
    min: 0,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "marginTop",
    label: "Margin Top",
    type: "number",
    category: "spacing",
    responsive: true,
    min: -100,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "marginRight",
    label: "Margin Right",
    type: "number",
    category: "spacing",
    responsive: true,
    min: -100,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "marginBottom",
    label: "Margin Bottom",
    type: "number",
    category: "spacing",
    responsive: true,
    min: -100,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
  {
    key: "marginLeft",
    label: "Margin Left",
    type: "number",
    category: "spacing",
    responsive: true,
    min: -100,
    max: 200,
    step: 4,
    defaultValue: 0,
  },
];

export const commonTypographySchema: PropertyFieldConfig[] = [
  {
    key: "fontSize",
    label: "Font Size (px)",
    type: "number",
    category: "typography",
    responsive: true,
    min: 10,
    max: 120,
    step: 1,
    defaultValue: 16,
  },
  {
    key: "fontWeight",
    label: "Font Weight",
    type: "select",
    category: "typography",
    options: [
      { label: "Light (300)", value: "300" },
      { label: "Normal (400)", value: "400" },
      { label: "Medium (500)", value: "500" },
      { label: "Semibold (600)", value: "600" },
      { label: "Bold (700)", value: "700" },
      { label: "Extrabold (800)", value: "800" },
    ],
    defaultValue: "400",
  },
  {
    key: "color",
    label: "Text Color",
    type: "color",
    category: "typography",
    defaultValue: "#1e293b",
  },
  {
    key: "textAlign",
    label: "Text Align",
    type: "select",
    category: "typography",
    responsive: true,
    options: [
      { label: "Left", value: "left" },
      { label: "Center", value: "center" },
      { label: "Right", value: "right" },
      { label: "Justify", value: "justify" },
    ],
    defaultValue: "left",
  },
  {
    key: "lineHeight",
    label: "Line Height",
    type: "text",
    category: "typography",
    placeholder: "1.2, 1.5, 24px",
    defaultValue: "1.5",
  },
  {
    key: "letterSpacing",
    label: "Letter Spacing",
    type: "text",
    category: "typography",
    placeholder: "normal, -0.02em, 1px",
    defaultValue: "normal",
  },
];

export const commonBackgroundSchema: PropertyFieldConfig[] = [
  {
    key: "backgroundColor",
    label: "Background Color",
    type: "color",
    category: "background",
    defaultValue: "transparent",
  },
  {
    key: "backgroundImage",
    label: "Background Image URL",
    type: "image",
    category: "background",
    placeholder: "https://images.unsplash.com/...",
  },
  {
    key: "backgroundSize",
    label: "Background Size",
    type: "select",
    category: "background",
    options: [
      { label: "Cover", value: "cover" },
      { label: "Contain", value: "contain" },
      { label: "Auto", value: "auto" },
    ],
    defaultValue: "cover",
  },
  {
    key: "backgroundPosition",
    label: "Background Position",
    type: "select",
    category: "background",
    options: [
      { label: "Center", value: "center" },
      { label: "Top", value: "top" },
      { label: "Bottom", value: "bottom" },
    ],
    defaultValue: "center",
  },
];

export const commonBorderSchema: PropertyFieldConfig[] = [
  {
    key: "borderWidth",
    label: "Border Width (px)",
    type: "number",
    category: "border",
    min: 0,
    max: 20,
    defaultValue: 0,
  },
  {
    key: "borderStyle",
    label: "Border Style",
    type: "select",
    category: "border",
    options: [
      { label: "Solid", value: "solid" },
      { label: "Dashed", value: "dashed" },
      { label: "Dotted", value: "dotted" },
      { label: "None", value: "none" },
    ],
    defaultValue: "solid",
  },
  {
    key: "borderColor",
    label: "Border Color",
    type: "color",
    category: "border",
    defaultValue: "#e2e8f0",
  },
  {
    key: "borderRadius",
    label: "Border Radius (px)",
    type: "number",
    category: "border",
    min: 0,
    max: 100,
    step: 2,
    defaultValue: 0,
  },
];

export const commonShadowSchema: PropertyFieldConfig[] = [
  {
    key: "boxShadow",
    label: "Box Shadow Preset",
    type: "select",
    category: "shadow",
    options: [
      { label: "None", value: "none" },
      { label: "Subtle (sm)", value: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
      { label: "Medium (md)", value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)" },
      { label: "Large (lg)", value: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)" },
      { label: "Extra Large (xl)", value: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)" },
      { label: "Glow Accent", value: "0 0 25px -5px rgba(59, 130, 246, 0.4)" },
      { label: "Dark Shadow", value: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" },
    ],
    defaultValue: "none",
  },
  {
    key: "opacity",
    label: "Opacity",
    type: "number",
    category: "effects",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: 1,
  },
];
