import { ComponentDefinition, ElementType } from "@/types/editor";
import {
  commonBackgroundSchema,
  commonBorderSchema,
  commonLayoutSchema,
  commonShadowSchema,
  commonSpacingSchema,
  commonTypographySchema,
} from "./property-schemas";

export const COMPONENT_REGISTRY: Record<ElementType, ComponentDefinition> = {
  section: {
    type: "section",
    label: "Section",
    category: "layout",
    iconName: "Layout",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      width: "100%",
      minHeight: "auto",
      paddingTop: 64,
      paddingBottom: 64,
      paddingLeft: 24,
      paddingRight: 24,
      backgroundColor: "#ffffff",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      overflow: "visible",
    },
    schema: [
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  container: {
    type: "container",
    label: "Container",
    category: "layout",
    iconName: "Box",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      width: "100%",
      maxWidth: "1200px",
      display: "flex",
      flexDirection: "column",
      gap: 24,
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 16,
      paddingRight: 16,
      alignItems: "stretch",
      justifyContent: "flex-start",
    },
    schema: [
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  columns: {
    type: "columns",
    label: "Columns",
    category: "layout",
    iconName: "Columns3",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      width: "100%",
      columnsCount: 2,
      gap: 24,
      stackOnMobile: true,
      display: "grid",
      paddingTop: 8,
      paddingBottom: 8,
      paddingLeft: 0,
      paddingRight: 0,
    },
    schema: [
      {
        key: "columnsCount",
        label: "Number of Columns",
        type: "select",
        category: "layout",
        options: [
          { label: "2 Columns", value: 2 },
          { label: "3 Columns", value: 3 },
          { label: "4 Columns", value: 4 },
        ],
        defaultValue: 2,
      },
      {
        key: "stackOnMobile",
        label: "Stack on Mobile/Tablet",
        type: "toggle",
        category: "layout",
        defaultValue: true,
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
      ...commonBorderSchema,
    ],
  },

  grid: {
    type: "grid",
    label: "Grid Layout",
    category: "layout",
    iconName: "Grid",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      width: "100%",
      gridCols: 3,
      gap: 24,
      paddingTop: 12,
      paddingBottom: 12,
    },
    schema: [
      {
        key: "gridCols",
        label: "Grid Columns",
        type: "number",
        category: "layout",
        responsive: true,
        min: 1,
        max: 6,
        step: 1,
        defaultValue: 3,
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
    ],
  },

  spacer: {
    type: "spacer",
    label: "Spacer",
    category: "layout",
    iconName: "MoveVertical",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      height: 48,
      width: "100%",
    },
    schema: [
      {
        key: "height",
        label: "Height (px)",
        type: "number",
        category: "layout",
        responsive: true,
        min: 4,
        max: 300,
        step: 8,
        defaultValue: 48,
      },
    ],
  },

  heading: {
    type: "heading",
    label: "Heading",
    category: "typography",
    iconName: "Heading",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      text: "Craft Stunning Web Experiences",
      tag: "h2",
      fontSize: 42,
      fontWeight: "700",
      color: "#0f172a",
      textAlign: "left",
      lineHeight: "1.2",
      letterSpacing: "-0.02em",
      marginTop: 0,
      marginBottom: 12,
    },
    schema: [
      {
        key: "text",
        label: "Heading Text",
        type: "text",
        category: "custom",
        defaultValue: "Craft Stunning Web Experiences",
      },
      {
        key: "tag",
        label: "HTML Tag",
        type: "select",
        category: "custom",
        options: [
          { label: "H1 - Primary Title", value: "h1" },
          { label: "H2 - Section Title", value: "h2" },
          { label: "H3 - Sub Heading", value: "h3" },
          { label: "H4 - Card Heading", value: "h4" },
          { label: "H5 - Small Heading", value: "h5" },
          { label: "H6 - Micro Heading", value: "h6" },
        ],
        defaultValue: "h2",
      },
      ...commonTypographySchema,
      ...commonSpacingSchema,
    ],
  },

  paragraph: {
    type: "paragraph",
    label: "Paragraph",
    category: "typography",
    iconName: "AlignLeft",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      text: "SiteForge empowers modern teams to design, launch, and publish high-performance websites with a powerful visual engine.",
      fontSize: 18,
      fontWeight: "400",
      color: "#475569",
      textAlign: "left",
      lineHeight: "1.6",
      marginTop: 0,
      marginBottom: 16,
    },
    schema: [
      {
        key: "text",
        label: "Paragraph Text",
        type: "textarea",
        category: "custom",
        defaultValue: "SiteForge empowers modern teams to design, launch, and publish high-performance websites with a powerful visual engine.",
      },
      ...commonTypographySchema,
      ...commonSpacingSchema,
    ],
  },

  text: {
    type: "text",
    label: "Text Badge / Span",
    category: "typography",
    iconName: "Type",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      text: "✨ NEW RELEASE 2.0",
      fontSize: 14,
      fontWeight: "600",
      color: "#2563eb",
      backgroundColor: "#eff6ff",
      paddingTop: 6,
      paddingBottom: 6,
      paddingLeft: 12,
      paddingRight: 12,
      borderRadius: 9999,
      borderWidth: 1,
      borderColor: "#bfdbfe",
      display: "inline-block",
      marginBottom: 8,
    },
    schema: [
      {
        key: "text",
        label: "Text Content",
        type: "text",
        category: "custom",
        defaultValue: "✨ NEW RELEASE 2.0",
      },
      ...commonTypographySchema,
      ...commonBackgroundSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
    ],
  },

  link: {
    type: "link",
    label: "Link",
    category: "typography",
    iconName: "Link2",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      text: "Explore features →",
      href: "#",
      target: "_self",
      fontSize: 16,
      fontWeight: "500",
      color: "#2563eb",
      textDecoration: "none",
    },
    schema: [
      {
        key: "text",
        label: "Link Text",
        type: "text",
        category: "custom",
        defaultValue: "Explore features →",
      },
      {
        key: "href",
        label: "Target URL / Anchor",
        type: "text",
        category: "custom",
        defaultValue: "#",
      },
      {
        key: "target",
        label: "Open Behavior",
        type: "select",
        category: "custom",
        options: [
          { label: "Same Tab (_self)", value: "_self" },
          { label: "New Tab (_blank)", value: "_blank" },
        ],
        defaultValue: "_self",
      },
      ...commonTypographySchema,
      ...commonSpacingSchema,
    ],
  },

  image: {
    type: "image",
    label: "Image",
    category: "media",
    iconName: "Image",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
      alt: "Dashboard showcase",
      width: "100%",
      maxWidth: "100%",
      height: "auto",
      borderRadius: 12,
      boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
      objectFit: "cover",
      borderWidth: 1,
      borderColor: "#e2e8f0",
      marginTop: 8,
      marginBottom: 8,
    },
    schema: [
      {
        key: "src",
        label: "Image URL",
        type: "image",
        category: "custom",
        defaultValue: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
      },
      {
        key: "alt",
        label: "Alt Description",
        type: "text",
        category: "custom",
        defaultValue: "Dashboard showcase",
      },
      {
        key: "objectFit",
        label: "Object Fit",
        type: "select",
        category: "custom",
        options: [
          { label: "Cover", value: "cover" },
          { label: "Contain", value: "contain" },
          { label: "Fill", value: "fill" },
        ],
        defaultValue: "cover",
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  video: {
    type: "video",
    label: "Video Embed",
    category: "media",
    iconName: "Video",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      aspectRatio: "16/9",
      width: "100%",
      maxWidth: "800px",
      borderRadius: 12,
      boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
    },
    schema: [
      {
        key: "embedUrl",
        label: "Video Embed URL (YouTube/Vimeo/Direct)",
        type: "text",
        category: "custom",
        defaultValue: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      {
        key: "aspectRatio",
        label: "Aspect Ratio",
        type: "select",
        category: "custom",
        options: [
          { label: "16:9 (Standard Widescreen)", value: "16/9" },
          { label: "4:3 (Classic)", value: "4/3" },
          { label: "1:1 (Square)", value: "1/1" },
          { label: "9:16 (Vertical / Reel)", value: "9/16" },
        ],
        defaultValue: "16/9",
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  gallery: {
    type: "gallery",
    label: "Image Gallery",
    category: "media",
    iconName: "Images",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      images: [
        "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=80",
      ],
      columnsCount: 3,
      gap: 16,
      borderRadius: 12,
      height: 240,
    },
    schema: [
      {
        key: "columnsCount",
        label: "Columns",
        type: "select",
        category: "layout",
        options: [
          { label: "2 Columns", value: 2 },
          { label: "3 Columns", value: 3 },
          { label: "4 Columns", value: 4 },
        ],
        defaultValue: 3,
      },
      {
        key: "height",
        label: "Item Height (px)",
        type: "number",
        category: "layout",
        min: 100,
        max: 600,
        step: 20,
        defaultValue: 240,
      },
      ...commonSpacingSchema,
      ...commonBorderSchema,
    ],
  },

  button: {
    type: "button",
    label: "Button",
    category: "interactive",
    iconName: "MousePointerClick",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      text: "Get Started Free",
      href: "#",
      target: "_self",
      variant: "solid",
      backgroundColor: "#2563eb",
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "600",
      paddingTop: 14,
      paddingBottom: 14,
      paddingLeft: 28,
      paddingRight: 28,
      borderRadius: 8,
      borderWidth: 0,
      borderColor: "transparent",
      boxShadow: "0 4px 6px -1px rgba(37, 99, 235, 0.2)",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
    },
    schema: [
      {
        key: "text",
        label: "Button Text",
        type: "text",
        category: "custom",
        defaultValue: "Get Started Free",
      },
      {
        key: "href",
        label: "Link / Target URL",
        type: "text",
        category: "custom",
        defaultValue: "#",
      },
      {
        key: "target",
        label: "Open in New Tab",
        type: "select",
        category: "custom",
        options: [
          { label: "No (Same Window)", value: "_self" },
          { label: "Yes (New Tab)", value: "_blank" },
        ],
        defaultValue: "_self",
      },
      {
        key: "variant",
        label: "Style Variant",
        type: "select",
        category: "custom",
        options: [
          { label: "Solid Primary", value: "solid" },
          { label: "Outline", value: "outline" },
          { label: "Ghost", value: "ghost" },
          { label: "Glassmorphic", value: "glass" },
        ],
        defaultValue: "solid",
      },
      ...commonTypographySchema,
      ...commonBackgroundSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  input: {
    type: "input",
    label: "Input Field",
    category: "interactive",
    iconName: "FormInput",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      placeholder: "Enter your email address...",
      label: "Work Email",
      inputType: "email",
      required: true,
      width: "100%",
      paddingTop: 12,
      paddingBottom: 12,
      paddingLeft: 16,
      paddingRight: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      backgroundColor: "#ffffff",
      color: "#0f172a",
      fontSize: 15,
    },
    schema: [
      {
        key: "label",
        label: "Field Label",
        type: "text",
        category: "custom",
        defaultValue: "Work Email",
      },
      {
        key: "placeholder",
        label: "Placeholder Text",
        type: "text",
        category: "custom",
        defaultValue: "Enter your email address...",
      },
      {
        key: "inputType",
        label: "Input Type",
        type: "select",
        category: "custom",
        options: [
          { label: "Email", value: "email" },
          { label: "Text", value: "text" },
          { label: "Phone (Tel)", value: "tel" },
          { label: "Number", value: "number" },
          { label: "Textarea", value: "textarea" },
        ],
        defaultValue: "email",
      },
      {
        key: "required",
        label: "Is Required",
        type: "toggle",
        category: "custom",
        defaultValue: true,
      },
      ...commonTypographySchema,
      ...commonBackgroundSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
    ],
  },

  form: {
    type: "form",
    label: "Lead Capture Form",
    category: "interactive",
    iconName: "SquareCheck",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      title: "Get in Touch with our Team",
      description: "Fill out the form below and we'll get back to you within 24 hours.",
      buttonText: "Submit Request",
      successMessage: "Thank you! We have received your message.",
      width: "100%",
      maxWidth: "540px",
      backgroundColor: "#ffffff",
      paddingTop: 32,
      paddingBottom: 32,
      paddingLeft: 32,
      paddingRight: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: "#e2e8f0",
      boxShadow: "0 20px 25px -5px rgb(0 0 0 / 0.1)",
    },
    schema: [
      {
        key: "title",
        label: "Form Title",
        type: "text",
        category: "custom",
        defaultValue: "Get in Touch with our Team",
      },
      {
        key: "description",
        label: "Form Subtitle",
        type: "textarea",
        category: "custom",
        defaultValue: "Fill out the form below and we'll get back to you within 24 hours.",
      },
      {
        key: "buttonText",
        label: "Submit Button Text",
        type: "text",
        category: "custom",
        defaultValue: "Submit Request",
      },
      {
        key: "successMessage",
        label: "Success Message",
        type: "text",
        category: "custom",
        defaultValue: "Thank you! We have received your message.",
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  card: {
    type: "card",
    label: "Card Box",
    category: "content",
    iconName: "CreditCard",
    canHaveChildren: true,
    allowedChildren: "all",
    defaultProps: {
      width: "100%",
      backgroundColor: "#ffffff",
      paddingTop: 28,
      paddingBottom: 28,
      paddingLeft: 28,
      paddingRight: 28,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: "#f1f5f9",
      boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.05)",
      display: "flex",
      flexDirection: "column",
      gap: 16,
      overflow: "hidden",
    },
    schema: [
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBackgroundSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  divider: {
    type: "divider",
    label: "Divider",
    category: "content",
    iconName: "Minus",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      width: "100%",
      borderWidth: 1,
      borderColor: "#e2e8f0",
      borderStyle: "solid",
      marginTop: 24,
      marginBottom: 24,
    },
    schema: [
      {
        key: "width",
        label: "Divider Width",
        type: "text",
        category: "layout",
        defaultValue: "100%",
      },
      ...commonBorderSchema,
      ...commonSpacingSchema,
    ],
  },

  faq: {
    type: "faq",
    label: "FAQ Accordion",
    category: "content",
    iconName: "HelpCircle",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      items: [
        {
          question: "How does SiteForge work?",
          answer: "SiteForge allows you to build responsive pages with visual elements, manage multi-page sites, save drafts, and publish to public endpoints instantly.",
        },
        {
          question: "Can I customize every element?",
          answer: "Yes! Use the right properties panel to customize layout, typography, colors, borders, spacing, shadows, and device breakpoints.",
        },
        {
          question: "Is published content secure and isolated from drafts?",
          answer: "Absolutely. Public users only see published version snapshots. Draft edits remain strictly private to the authenticated admin.",
        },
      ],
      width: "100%",
      maxWidth: "800px",
      itemBackgroundColor: "#f8fafc",
      borderRadius: 12,
      borderColor: "#e2e8f0",
      borderWidth: 1,
    },
    schema: [
      {
        key: "items",
        label: "Questions & Answers",
        type: "faq-list",
        category: "custom",
      },
      ...commonLayoutSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
    ],
  },

  navbar: {
    type: "navbar",
    label: "Navigation Bar",
    category: "navigation",
    iconName: "Navigation",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      brandText: "SiteForge",
      logoUrl: "",
      links: [
        { label: "Features", href: "#features" },
        { label: "Solutions", href: "#solutions" },
        { label: "Pricing", href: "#pricing" },
        { label: "About", href: "/about" },
      ],
      ctaText: "Get Started",
      ctaHref: "#signup",
      backgroundColor: "#ffffff",
      textColor: "#0f172a",
      width: "100%",
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 32,
      paddingRight: 32,
      borderBottomWidth: 1,
      borderBottomColor: "#e2e8f0",
      sticky: true,
      boxShadow: "0 1px 3px 0 rgb(0 0 0 / 0.05)",
    },
    schema: [
      {
        key: "brandText",
        label: "Brand / Logo Name",
        type: "text",
        category: "custom",
        defaultValue: "SiteForge",
      },
      {
        key: "logoUrl",
        label: "Logo Image URL (Optional)",
        type: "image",
        category: "custom",
      },
      {
        key: "links",
        label: "Navigation Links",
        type: "links-list",
        category: "custom",
      },
      {
        key: "ctaText",
        label: "CTA Button Text",
        type: "text",
        category: "custom",
        defaultValue: "Get Started",
      },
      {
        key: "ctaHref",
        label: "CTA Button URL",
        type: "text",
        category: "custom",
        defaultValue: "#signup",
      },
      {
        key: "sticky",
        label: "Sticky Top Header",
        type: "toggle",
        category: "custom",
        defaultValue: true,
      },
      ...commonBackgroundSchema,
      ...commonSpacingSchema,
      ...commonBorderSchema,
      ...commonShadowSchema,
    ],
  },

  footer: {
    type: "footer",
    label: "Footer",
    category: "navigation",
    iconName: "PanelBottom",
    canHaveChildren: false,
    allowedChildren: "none",
    defaultProps: {
      brandText: "SiteForge Studio",
      description: "Next-generation visual website publishing platform.",
      copyright: "© 2026 SiteForge. All rights reserved.",
      links: [
        { label: "Privacy Policy", href: "#privacy" },
        { label: "Terms of Service", href: "#terms" },
        { label: "Documentation", href: "#docs" },
        { label: "Contact Support", href: "#contact" },
      ],
      backgroundColor: "#0f172a",
      textColor: "#94a3b8",
      brandColor: "#ffffff",
      width: "100%",
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 32,
      paddingRight: 32,
      borderTopWidth: 1,
      borderTopColor: "#1e293b",
    },
    schema: [
      {
        key: "brandText",
        label: "Brand Name",
        type: "text",
        category: "custom",
        defaultValue: "SiteForge Studio",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        category: "custom",
        defaultValue: "Next-generation visual website publishing platform.",
      },
      {
        key: "copyright",
        label: "Copyright Text",
        type: "text",
        category: "custom",
        defaultValue: "© 2026 SiteForge. All rights reserved.",
      },
      {
        key: "links",
        label: "Footer Links",
        type: "links-list",
        category: "custom",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        category: "background",
        defaultValue: "#0f172a",
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "color",
        category: "typography",
        defaultValue: "#94a3b8",
      },
      ...commonSpacingSchema,
      ...commonBorderSchema,
    ],
  },
};
